// constraints.js
// Handles the weekly-availability page for both roles:
// - Employees: fill in availability for all 7 days at once in a single
//   form, against the currently open week.
// - Managers: open a new week manually, and review one weekly card per
//   employee, each showing all 7 days inline, with approve/reject.

const WEEK_DAYS = ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת'];

let currentOpenWeek = null;

function formatStatusLabel(status) {
  if (status === 'approved') return 'אושר';
  if (status === 'rejected') return 'נדחה';
  return 'ממתין';
}

// Classifies a free-text day note so cells can be color-coded without
// requiring the employee to pick from a rigid dropdown — "לא פנוי" /
// "לא" anywhere in the text reads as unavailable, "פנוי" reads as
// available, anything else (or empty) stays neutral.
function classifyNote(note) {
  if (!note || !note.trim()) return 'empty';
  if (/לא\s*פנוי|לא\s*זמין/.test(note)) return 'unavailable';
  if (/פנוי|זמין/.test(note)) return 'available';
  return 'neutral';
}

async function loadOpenWeek() {
  const labelEl = document.getElementById('weekBannerLabel');
  const subEl = document.getElementById('weekBannerSub');
  if (!labelEl) return;

  try {
    const res = await api('/api/weeks/open');
    currentOpenWeek = res.data;

    if (!currentOpenWeek) {
      labelEl.textContent = 'אין שבוע פתוח כרגע';
      subEl.textContent = 'פנו למנהל לפתיחת שבוע חדש';
      return;
    }

    labelEl.textContent = currentOpenWeek.label;
    subEl.textContent = currentOpenWeek.isAutoGenerated
      ? 'נפתח אוטומטית בתחילת השבוע'
      : 'נפתח על ידי המנהל';

  } catch (err) {
    labelEl.textContent = 'לא ניתן לטעון את השבוע הפתוח';
    subEl.textContent = '';
  }
}

// ───────────────────────── Employee: the weekly form ─────────────────────────

function buildAvailabilityGrid(existingDays = []) {
  const grid = document.getElementById('availabilityGrid');
  if (!grid) return;

  grid.innerHTML = WEEK_DAYS.map(day => {
    const existing = existingDays.find(d => d.day === day);
    const note = existing?.note || '';
    const hasNote = note.trim().length > 0;

    return `
      <div class="day-row${hasNote ? ' has-note' : ''}" data-day="${day}">
        <span class="day-label"><span class="day-dot"></span>${day}</span>
        <input type="text" class="day-note-input" data-day="${day}"
               value="${note.replace(/"/g, '&quot;')}"
               placeholder="לדוגמה: פנוי כל היום / לא פנוי בבוקר / לא פנוי">
      </div>
    `;
  }).join('');

  // Toggle the little status dot live as the employee types.
  grid.querySelectorAll('.day-note-input').forEach(input => {
    input.addEventListener('input', () => {
      const row = input.closest('.day-row');
      row.classList.toggle('has-note', input.value.trim().length > 0);
    });
  });
}

async function loadExistingSubmissionIntoForm() {
  if (!currentOpenWeek) {
    buildAvailabilityGrid([]);
    return;
  }

  try {
    const res = await api(`/api/weekly-availability/mine?week=${currentOpenWeek._id}`);
    buildAvailabilityGrid(res.data?.days || []);
  } catch (err) {
    buildAvailabilityGrid([]);
  }
}

function setupAvailabilityForm() {
  const form = document.getElementById('availabilityForm');
  if (!form) return;

  form.addEventListener('submit', async (event) => {
    event.preventDefault();

    if (!currentOpenWeek) {
      showMessage('אין שבוע פתוח להגשה כרגע', 'error');
      return;
    }

    const days = Array.from(document.querySelectorAll('.day-note-input')).map(input => ({
      day: input.dataset.day,
      note: input.value.trim()
    }));

    try {
      await api('/api/weekly-availability', {
        method: 'POST',
        body: JSON.stringify({ week: currentOpenWeek._id, days })
      });

      showMessage('הזמינות נשלחה בהצלחה לשבוע הפתוח');
      loadMyAvailability();

    } catch (err) {
      showMessage(err.message, 'error');
    }
  });
}

// ───────────────────────── Employee: "my availability" summary ─────────────────────────

function renderMyAvailabilityCard(submission) {
  const cells = WEEK_DAYS.map(day => {
    const dayData = submission.days.find(d => d.day === day) || { note: '' };
    const cls = classifyNote(dayData.note);
    return `
      <div class="day-summary-cell ${cls === 'empty' ? 'empty' : ''} ${cls === 'unavailable' ? 'unavailable' : ''}">
        <span class="ds-day">${day}</span>
        <span class="ds-note">${dayData.note || '—'}</span>
      </div>
    `;
  }).join('');

  return `
    <div class="my-week-card">
      <div class="week-row-header">
        <span class="week-title">${submission.week?.label || ''}</span>
        <span class="status-pill ${submission.status}">${formatStatusLabel(submission.status)}</span>
      </div>
      <div class="day-summary-grid">${cells}</div>
    </div>
  `;
}

async function loadMyAvailability() {
  const box = document.getElementById('myAvailabilityBox');
  if (!box) return;

  try {
    const res = await api('/api/weekly-availability');

    if (res.data.length === 0) {
      box.innerHTML = '<p class="empty-message">עדיין לא הוגשה זמינות</p>';
      return;
    }

    box.innerHTML = res.data.map(renderMyAvailabilityCard).join('');

  } catch (err) {
    box.innerHTML = '<p class="empty-message">יש להתחבר כדי לצפות בזמינות שלך</p>';
  }
}

// ───────────────────────── Manager: team weekly review ─────────────────────────

function renderManagerWeekCard(submission) {
  const cells = WEEK_DAYS.map(day => {
    const dayData = submission.days.find(d => d.day === day) || { note: '' };
    const cls = classifyNote(dayData.note);
    return `
      <div class="day-cell ${cls === 'empty' ? 'empty' : ''} ${cls === 'unavailable' ? 'unavailable' : ''} ${cls === 'available' ? 'available' : ''}">
        <span class="dc-day">${day}</span>
        <span class="dc-note">${dayData.note || '—'}</span>
      </div>
    `;
  }).join('');

  const actionButtons = submission.status === 'pending'
    ? `<button class="icon-btn approve" onclick="reviewWeeklySubmission('${submission._id}', 'approved')">אישור</button>
       <button class="icon-btn reject" onclick="reviewWeeklySubmission('${submission._id}', 'rejected')">דחייה</button>`
    : `<span class="status-pill ${submission.status}" style="background:rgba(255,255,255,0.15);color:#fff">${formatStatusLabel(submission.status)}</span>`;

  return `
    <div class="employee-week-card">
      <div class="ewc-header">
        <div>
          <span class="ewc-name">${submission.employee?.fullName || 'עובד'}</span>
          <span class="ewc-dept">${submission.employee?.department || ''}</span>
        </div>
        <div class="ewc-actions">${actionButtons}</div>
      </div>
      <div class="day-cell-grid">${cells}</div>
    </div>
  `;
}

// Renders the "X out of Y submitted" progress bar plus chips for anyone
// who hasn't submitted yet, so the manager knows exactly who to chase.
function renderProgressSummary(allEmployees, submissions) {
  const submittedIds = new Set(submissions.map(s => String(s.employee?._id)));
  const missing = allEmployees.filter(e => !submittedIds.has(String(e._id)));

  const total = allEmployees.length;
  const submittedCount = total - missing.length;
  const pct = total > 0 ? Math.round((submittedCount / total) * 100) : 0;
  const isComplete = total > 0 && missing.length === 0;

  const missingChips = missing.length
    ? `<div class="missing-list">${missing.map(e => `<span class="missing-chip">${e.fullName} — לא הגיש/ה</span>`).join('')}</div>`
    : '';

  return `
    <div class="progress-summary">
      <div class="ps-header">
        <span class="ps-title">הגשות לשבוע הפתוח</span>
        <span class="ps-count">${submittedCount} / ${total}</span>
      </div>
      <div class="progress-bar-track">
        <div class="progress-bar-fill${isComplete ? ' complete' : ''}" style="width:${pct}%"></div>
      </div>
      ${missingChips}
    </div>
  `;
}

async function loadProgressSummary() {
  const container = document.getElementById('progressSummaryBox');
  if (!container || !currentOpenWeek) return;

  try {
    const [usersRes, submissionsRes] = await Promise.all([
      api('/api/users?role=employee'),
      api('/api/weekly-availability?week=' + currentOpenWeek._id)
    ]);

    container.innerHTML = renderProgressSummary(usersRes.data, submissionsRes.data);

  } catch (err) {
    container.innerHTML = '';
  }
}

async function loadManagerWeeklyList() {
  const list = document.getElementById('managerWeeklyList');
  if (!list || !currentOpenWeek) return;

  try {
    const res = await api('/api/weekly-availability?week=' + currentOpenWeek._id);

    if (res.data.length === 0) {
      list.innerHTML = '<p class="empty-message">אין הגשות זמינות לשבוע הפתוח</p>';
      return;
    }

    list.innerHTML = res.data.map(renderManagerWeekCard).join('');

  } catch (err) {
    list.innerHTML = `<p class="empty-message">${err.message}</p>`;
  }
}

async function reviewWeeklySubmission(id, status) {
  try {
    await api(`/api/weekly-availability/${id}/status`, {
      method: 'PATCH',
      body: JSON.stringify({ status })
    });
    loadManagerWeeklyList();
  } catch (err) {
    alert(err.message);
  }
}

function setupOpenWeekForm() {
  const form = document.getElementById('openWeekForm');
  if (!form) return;

  form.addEventListener('submit', async (event) => {
    event.preventDefault();

    const startDate = document.getElementById('newWeekStart').value;

    try {
      await api('/api/weeks', {
        method: 'POST',
        body: JSON.stringify({ startDate })
      });

      await loadOpenWeek();
      await loadManagerWeeklyList();
      await loadProgressSummary();
      form.reset();

    } catch (err) {
      alert(err.message);
    }
  });
}

function setupManagerSections() {
  const user = getCurrentUser();
  if (!user || user.role !== 'manager') return;

  document.getElementById('employeeSubmitSection')?.classList.add('hidden');
  document.getElementById('managerWeekSection')?.classList.remove('hidden');
  document.getElementById('managerReviewSection')?.classList.remove('hidden');

  setupOpenWeekForm();
  loadManagerWeeklyList();
  loadProgressSummary();
}

// expose for inline onclick handlers
window.reviewWeeklySubmission = reviewWeeklySubmission;

(async function initConstraintsPage() {
  await loadOpenWeek();
  setupAvailabilityForm();
  await loadExistingSubmissionIntoForm();
  loadMyAvailability();
  setupManagerSections();
})();
