import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { connectDB } from './config/db.js';
import User from './models/User.js';
import Shift from './models/Shift.js';
import Constraint from './models/Constraint.js';
import WeekPeriod from './models/WeekPeriod.js';
import WeeklyAvailability from './models/WeeklyAvailability.js';

dotenv.config();

await connectDB();

await User.deleteMany();
await Shift.deleteMany();
await Constraint.deleteMany();
await WeekPeriod.deleteMany();
await WeeklyAvailability.deleteMany();

const manager = await User.create({
  fullName: 'עומר לחאם',
  email: 'manager@shiftplan.com',
  password: '123456',
  role: 'manager',
  department: 'ניהול'
});

const employee1 = await User.create({
  fullName: 'עבדאללה עיד',
  email: 'employee@shiftplan.com',
  password: '123456',
  role: 'employee',
  department: 'שירות'
});

const employee2 = await User.create({
  fullName: 'אמיר אבו עגל',
  email: 'amir@shiftplan.com',
  password: '123456',
  role: 'employee',
  department: 'קופה'
});

const employee3 = await User.create({
  fullName: 'מוחמד אגבאריה',
  email: 'mohammad@shiftplan.com',
  password: '123456',
  role: 'employee',
  department: 'לוגיסטיקה'
});

const employees = [employee1, employee2, employee3];

function formatWeekLabel(start, end) {
  const fmt = (d) => `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}`;
  return `${fmt(start)} - ${fmt(end)}`;
}

const weekStart = new Date();
weekStart.setHours(0, 0, 0, 0);
const weekEnd = new Date(weekStart);
weekEnd.setDate(weekEnd.getDate() + 6);
weekEnd.setHours(23, 59, 59, 999);

const currentWeek = await WeekPeriod.create({
  startDate: weekStart,
  endDate: weekEnd,
  label: formatWeekLabel(weekStart, weekEnd),
  status: 'open',
  isAutoGenerated: false,
  createdBy: manager._id
});

await Shift.insertMany([
  {
    employee: manager._id,
    day: 'ראשון',
    start: '08:00',
    end: '16:00',
    role: 'מנהל משמרת',
    department: 'ניהול'
  },
  {
    employee: employees[0]._id,
    day: 'שני',
    start: '14:00',
    end: '22:00',
    role: 'נציג שירות',
    department: 'שירות'
  },
  {
    employee: employees[1]._id,
    day: 'שלישי',
    start: '09:00',
    end: '15:00',
    role: 'קופאי',
    department: 'קופה'
  },
  {
    employee: employees[2]._id,
    day: 'רביעי',
    start: '16:00',
    end: '22:00',
    role: 'מחסן',
    department: 'לוגיסטיקה'
  }
]);

await Constraint.create({
  employee: employees[0]._id,
  week: currentWeek._id,
  day: 'חמישי',
  preferredStart: '08:00',
  preferredEnd: '14:00',
  reason: 'לימודים'
});

await WeeklyAvailability.create({
  employee: employees[0]._id,
  week: currentWeek._id,
  days: [
    { day: 'ראשון', note: 'פנוי כל היום' },
    { day: 'שני', note: 'פנוי מ-14:00' },
    { day: 'שלישי', note: '' },
    { day: 'רביעי', note: 'לא פנוי - לימודים' },
    { day: 'חמישי', note: 'פנוי עד 14:00' },
    { day: 'שישי', note: '' },
    { day: 'שבת', note: 'לא פנוי' }
  ],
  status: 'pending'
});

await WeeklyAvailability.create({
  employee: employees[1]._id,
  week: currentWeek._id,
  days: [
    { day: 'ראשון', note: 'פנוי כל היום' },
    { day: 'שני', note: 'פנוי כל היום' },
    { day: 'שלישי', note: 'פנוי כל היום' },
    { day: 'רביעי', note: '' },
    { day: 'חמישי', note: '' },
    { day: 'שישי', note: 'לא פנוי - אירוע משפחתי' },
    { day: 'שבת', note: '' }
  ],
  status: 'approved'
});

console.log('Seed completed');

await mongoose.disconnect();