import mongoose from 'mongoose';

// A WeekPeriod represents one week that the manager has opened for
// employees to submit shift constraints against. Weeks can be created
// manually by a manager, or automatically once the previous week ends.
const weekPeriodSchema = new mongoose.Schema({
  startDate: { type: Date, required: true },
  endDate: { type: Date, required: true },
  label: { type: String, required: true }, // e.g. "07/06 - 13/06"
  status: { type: String, enum: ['open', 'closed'], default: 'open' },
  isAutoGenerated: { type: Boolean, default: false },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

export default mongoose.model('WeekPeriod', weekPeriodSchema);
