import WeekPeriod from '../models/WeekPeriod.js';
import { asyncHandler } from '../utils/asyncHandler.js';

// Hebrew-friendly date label, e.g. "07/06 - 13/06"
function formatWeekLabel(startDate, endDate) {
  const fmt = (d) => `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}`;
  return `${fmt(startDate)} - ${fmt(endDate)}`;
}

// Builds the next 7-day period starting the day after `fromDate`.
function buildNextWeekRange(fromDate) {
  const start = new Date(fromDate);
  start.setDate(start.getDate() + 1);
  start.setHours(0, 0, 0, 0);

  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  end.setHours(23, 59, 59, 999);

  return { start, end };
}

// Closes any week whose endDate has passed, and opens a new
// auto-generated week right after it if none is open yet.
// Called on server startup and before every "list weeks" request,
// which keeps the rollover logic simple without needing a cron job.
export async function rolloverWeeksIfNeeded() {
  const now = new Date();

  await WeekPeriod.updateMany(
    { status: 'open', endDate: { $lt: now } },
    { $set: { status: 'closed' } }
  );

  const openWeek = await WeekPeriod.findOne({ status: 'open' });
  if (openWeek) return;

  const lastWeek = await WeekPeriod.findOne().sort('-endDate');
  const { start, end } = lastWeek
    ? buildNextWeekRange(lastWeek.endDate)
    : buildNextWeekRange(new Date(now.getTime() - 24 * 60 * 60 * 1000));

  await WeekPeriod.create({
    startDate: start,
    endDate: end,
    label: formatWeekLabel(start, end),
    status: 'open',
    isAutoGenerated: true
  });
}

export const getWeeks = asyncHandler(async (req, res) => {
  await rolloverWeeksIfNeeded();
  const weeks = await WeekPeriod.find().sort('-startDate');
  res.json({ success: true, count: weeks.length, data: weeks });
});

export const getOpenWeek = asyncHandler(async (req, res) => {
  await rolloverWeeksIfNeeded();
  const week = await WeekPeriod.findOne({ status: 'open' }).sort('-startDate');
  res.json({ success: true, data: week });
});

export const openWeek = asyncHandler(async (req, res) => {
  const { startDate } = req.body;
  if (!startDate) {
    res.status(400);
    throw new Error('startDate is required');
  }

  const start = new Date(startDate);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  end.setHours(23, 59, 59, 999);

  // Closing any currently open week before opening a new one keeps
  // exactly one open week at a time, which simplifies the employee UI.
  await WeekPeriod.updateMany({ status: 'open' }, { $set: { status: 'closed' } });

  const week = await WeekPeriod.create({
    startDate: start,
    endDate: end,
    label: formatWeekLabel(start, end),
    status: 'open',
    isAutoGenerated: false,
    createdBy: req.user._id
  });

  res.status(201).json({ success: true, data: week });
});

export const closeWeek = asyncHandler(async (req, res) => {
  const week = await WeekPeriod.findByIdAndUpdate(
    req.params.id,
    { status: 'closed' },
    { new: true }
  );
  if (!week) {
    res.status(404);
    throw new Error('Week not found');
  }
  res.json({ success: true, data: week });
});
